import Navbar from '@/components/Navbar'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className='flex justify-center items-center h-screen my-9 py-2'>
          {children}
        </main>
      </body>
    </html>
  )
}
